# Generated by Django 6.0.6 on 2026-06-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedraft',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuedraft',
            name='completed_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
